version: '3'
services:

  redis:
    image: "redislabs/redismod:edge"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: jasonrocks
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: jasonrocks
      ME_CONFIG_MONGODB_URL: mongodb://admin:jasonrocks@mongo:27017/
