version: '3'
services:

  redis1:
    # image: myredis
    image: "redislabs/redismod:edge"
    container_name: redis1
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data1:/data

  redis2:
    # image: myredis
    image: "redislabs/redismod:edge"
    container_name: redis2
    ports:
      - "9001:9001"
    command: --port 9001
    volumes:
      - ./redis_data2:/data

