version: '3'
services:

  redis:
    # image: myredis
    image: "redislabs/redismod:edge"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  postgres:
    image: "postgres"
    # image: "arm64v8/postgres"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=jasonrocks
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    # image: "arm64v8/adminer"
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
