version: '3'
services:

  redis:
    image: "redislabs/redismod:edge"
    # image: myredis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  mysql:
    image: "mariadb"
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=jasonrocks
      - MYSQL_DATABASE=test
      - MYSQL_USER=demouser
      - MYSQL_PASSWORD=jasonrocks
    volumes:
      - ./mysqlDB:/var/lib/mysql

  adminer:
    # image: arm64v8/adminer
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
