version: '3'
services:

  redis:
    # image: myredis
    image: "redislabs/redismod:edge"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  db2:
    image: "ibmcom/db2"
    privileged: true
    container_name: db2
    restart: always
    ports:
      - "50000:50000"
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=jasonrocks
      - SAMPLEDB=true
    volumes:
      - ./db2_database:/database

#  could not get this to work even when pre-creating the db2repo repository
#  dmc:
#    image: "ibmcom/db2console"
#    container_name: dmc
#    restart: always
#    ports:
#      - "11081:8443"
#    environment:
#      - LICENSE=accept
#      - ADMIN_NAME=admin
#      - ADMIN_PASSWORD=jasonrocks
#      - MIGRATION=false
#      - REPO_HOST=db2
#      - REPO_PORT=50000
#      - REPO_DATABASE=db2repo
#      - REPO_USERNAME=db2inst1
#      - REPO_PASSWORD=jasonrocks
#    volumes:
#      - ./dmc_data:/mnt
#    depends_on:
#       - db2

  insight:
    image: "redislabs/redisinsight:latest"
    container_name: insight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis

# docker run -itd --name mydb2 --privileged=true -p 50000:50000 -e LICENSE=accept -e DB2INST1_PASSWORD=<choose an instance password> -e DBNAME=testdb -v <db storage dir>:/database ibmcom/db2
# docker run -d --name mydmc -p 11081:8443 -e LICENSE=accept -v <dmc storage dir>:/mnt -v /etc/localtime:/etc/localtime:ro ibmcom/db2console

